<?php

declare(strict_types=1);

namespace Propit\Normalizers;

use Propit\DTO\PublisherPayload;
use Propit\Exceptions\ValidationException;

/**
 * Validates and maps a PublisherPayload to the Proppit API body.
 *
 * Proppit Publisher schema (OpenAPI):
 *   required: [id]
 *   properties: id (string), name (string), email (string), phone (string)
 *
 * PHP field → API field:
 *   externalId → id   (the publisher identifier generated by Homlity)
 *   name       → name
 *   email      → email
 *   phone      → phone (optional)
 */
final class PublisherPayloadNormalizer
{
    public function normalize(PublisherPayload $payload): array
    {
        $externalId = trim($payload->externalId);

        if ($externalId === '') {
            throw new ValidationException('externalId is required and must not be empty.');
        }

        if (strlen($externalId) > 255) {
            throw new ValidationException('externalId must not exceed 255 characters.');
        }

        if (!preg_match('/^[\w\-\.@]+$/', $externalId)) {
            throw new ValidationException(
                'externalId contains invalid characters. Use only letters, digits, hyphens, underscores, dots, or @ (for email IDs).'
            );
        }

        $name = trim($payload->name);
        if ($name === '') {
            throw new ValidationException('publisher name is required and must not be empty.');
        }

        $email = trim($payload->email);
        if ($email === '') {
            throw new ValidationException('publisher email is required and must not be empty.');
        }

        $body = [
            'id'    => $externalId,
            'name'  => $name,
            'email' => $email,
        ];

        if ($payload->phone !== null && trim($payload->phone) !== '') {
            $body['phone'] = trim($payload->phone);
        }

        return $body;
    }
}
