<?php

declare(strict_types=1);

/**
 * sync_publisher.php
 *
 * Shows how to register or update an agency (publisher) in Proppit.
 *
 * IMPORTANT — publisher sent ≠ publisher active:
 *   After this script runs, the publisher is registered in Proppit but is NOT
 *   yet enabled to publish ads. Proppit must manually activate/connect the
 *   publisher before any ads can be sent.
 *
 *   Next step after running this script:
 *     1. Save the external_id and publisher_id returned below.
 *     2. Contact Proppit support using the template in docs/publisher-integration.md.
 *     3. Wait for Proppit to confirm activation.
 *     4. Only then run publish_property.php for this publisher.
 *
 * Flow:
 *   1. Load PROPIT_CLIENT_ID / PROPIT_CLIENT_SECRET from .env (system credentials).
 *   2. Generate the external_id for the agency using Homlity's internal ID.
 *   3. Call createOrUpdate() — creates the publisher if new, updates it if it exists.
 *   4. Check isPendingActivation() — it will be true after create/update.
 *   5. Persist the returned publisher ID and status in your inmobiliarias table.
 *
 * The consuming application (Homlity) is responsible for:
 *   - Generating the externalId: 'homlity_agency_' . $inmobiliaria->id (or uuid)
 *   - Persisting proppit_publisher_id, proppit_publisher_status, proppit_last_synced_at
 *   - NOT marking proppit_can_publish = true until Proppit confirms activation
 */

require __DIR__ . '/../vendor/autoload.php';

use GuzzleHttp\Client;
use Propit\Api\PublisherApi;
use Propit\Api\PropertyApi;
use Propit\Auth\ClientCredentialsAuthenticator;
use Propit\Config\PropitConfig;
use Propit\DTO\PublisherPayload;
use Propit\Exceptions\ApiException;
use Propit\Exceptions\AuthException;
use Propit\Exceptions\RateLimitException;
use Propit\Exceptions\ValidationException;
use Propit\Http\GuzzlePropitHttpClient;
use Propit\Normalizers\PropertyPayloadNormalizer;
use Propit\Normalizers\PublisherPayloadNormalizer;
use Propit\PropitClient;
use Propit\Support\StructuredLogger;

// ── 1. System-level configuration (from .env) ────────────────────────────────
// PROPIT_CLIENT_ID and PROPIT_CLIENT_SECRET are shared credentials for Homlity
// as an API client. They are NOT per-agency values.

$config = PropitConfig::fromArray([
    'base_url'      => getenv('PROPIT_BASE_URL') ?: 'https://real-time.proppit.com/api/v2',
    'client_id'     => getenv('PROPIT_CLIENT_ID') ?: '',
    'client_secret' => getenv('PROPIT_CLIENT_SECRET') ?: '',
    'country'       => getenv('PROPIT_COUNTRY') ?: 'CO',
    'timeout'       => (int) (getenv('PROPIT_TIMEOUT') ?: 30),
]);

// ── 2. Build the client stack ─────────────────────────────────────────────────

$guzzle = new Client();
$auth   = new ClientCredentialsAuthenticator($config, $guzzle);
$http   = new GuzzlePropitHttpClient($guzzle, $config, $auth, new StructuredLogger(false));

$client = new PropitClient(
    properties: new PropertyApi($http, new PropertyPayloadNormalizer(), $config),
    publishers: new PublisherApi($http, new PublisherPayloadNormalizer(), $config),
);

// ── 3. Build external_id for this agency ─────────────────────────────────────
// This should be generated by Homlity using the agency's stable internal ID or UUID.
//
// If the agency already has a proppit_external_id stored in the DB, use that value.
// Do NOT generate a new one — changing external_id breaks the Proppit link.
//
// Example: $externalId = $inmobiliaria->proppit_external_id
//       ?? 'homlity_agency_' . $inmobiliaria->uuid;

$agencyId   = (int) (getenv('DEMO_AGENCY_ID') ?: 123);
$externalId = 'homlity_agency_' . $agencyId;

// ── 4. Build the PublisherPayload ─────────────────────────────────────────────

$payload = new PublisherPayload(
    externalId: $externalId,
    name: getenv('DEMO_AGENCY_NAME') ?: 'Inmobiliaria Demo',
    email: getenv('DEMO_AGENCY_EMAIL') ?: 'contacto@inmobiliaria-demo.com',
    phone: getenv('DEMO_AGENCY_PHONE') ?: '+573001112233',
);

// ── 5. Register or update the publisher ──────────────────────────────────────

try {
    $response = $client->publishers()->createOrUpdate($payload);

    echo "Publisher synced with Proppit.\n";
    echo "externalId       : {$externalId}\n";
    echo "publisherId      : {$response->publisherId()}\n";
    echo "name             : {$response->name}\n";
    echo "activationStatus : {$response->activationStatus}\n";
    echo "canPublish       : " . ($response->canPublish() ? 'yes' : 'no') . "\n";

    // ── 6. Check activation state ─────────────────────────────────────────────
    if ($response->isPendingActivation()) {
        echo "\n⚠  Publisher enviado a Proppit pero AÚN NO está habilitado para publicar.\n";
        echo "   Debes solicitar a Proppit la activación del publisher antes de enviar anuncios.\n";
        echo "\n   Usa la plantilla en docs/publisher-integration.md para contactar a Proppit.\n";
        echo "   Incluye:\n";
        echo "     - external_id : {$externalId}\n";
        if ($response->publisherId() !== '') {
            echo "     - publisher_id: {$response->publisherId()}\n";
        }

        // ── 7. Persist as pending_activation ─────────────────────────────────
        // Example (Laravel Eloquent):
        //   $inmobiliaria->update([
        //       'proppit_external_id'      => $externalId,
        //       'proppit_publisher_id'     => $response->publisherId(),
        //       'proppit_publisher_status' => $response->activationStatus,
        //       'proppit_can_publish'      => false,   // ← NOT yet enabled
        //       'proppit_last_synced_at'   => now(),
        //       'proppit_last_error'       => null,
        //   ]);
    } else {
        echo "\n✓  Publisher activo — listo para enviar anuncios.\n";

        // ── 7. Persist as active ──────────────────────────────────────────────
        // Example (Laravel Eloquent):
        //   $inmobiliaria->update([
        //       'proppit_external_id'      => $externalId,
        //       'proppit_publisher_id'     => $response->publisherId(),
        //       'proppit_publisher_status' => $response->activationStatus,
        //       'proppit_can_publish'      => true,
        //       'proppit_last_synced_at'   => now(),
        //       'proppit_activated_at'     => now(),
        //       'proppit_last_error'       => null,
        //   ]);
    }

    echo "\nNext step: save proppit_publisher_id = '{$response->publisherId()}' in your inmobiliarias table.\n";
} catch (ValidationException $e) {
    echo "[ValidationException] " . $e->getMessage() . "\n";
    exit(1);
} catch (AuthException $e) {
    echo "[AuthException] " . $e->getMessage() . "\n";
    echo "Check PROPIT_CLIENT_ID and PROPIT_CLIENT_SECRET in your .env file.\n";
    exit(1);
} catch (RateLimitException $e) {
    $retry = $e->retryAfter ?? 'unknown';
    echo "[RateLimitException] Rate limit reached. Retry after {$retry}s.\n";
    exit(1);
} catch (ApiException $e) {
    echo "[ApiException] HTTP {$e->statusCode} on {$e->method} {$e->endpoint}: {$e->getMessage()}\n";
    exit(1);
}
